name: Docker build and push

on:
  push:
    branches: ["main"]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER_NAME: ruins
      IMAGE_NAME: cloudrun-blackbox-exporter
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
             ${{ env.DOCKERHUB_USER_NAME }}/${{ env.IMAGE_NAME }}:latest
